keys:
  - &chilipizdrick age16x4r43vfvgv26dzwgvhjg83hjajmrf0z7ej2z69wh7tpw5xdaaxstn2jmm
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *chilipizdrick
  - path_regex: secrets/bob.env$
    key_groups:
      - age:
        - *chilipizdrick
  - path_regex: secrets/schizophrenia-bot.env$
    key_groups:
      - age:
        - *chilipizdrick
